Repository svsticky/constipated-koala, pull requests merged in 2020-02, with the labels that each got.

#557 Add activity unavailable page
  app/controllers/members/activities_controller.rb
  app/views/members/activities/unavailable.html.haml
  config/locales/en.yml
  config/locales/nl.yml
Labels: enhancement, review

#568 Use d-none instead of hidden
  app/assets/javascripts/admin/activities.js
  app/views/admin/activities/partials/_attendee_table_row.html.haml
  app/views/admin/activities/show.html.haml
  app/views/admin/members/show.html.haml
  app/views/admin/payments/index.html.haml
Labels: 2.0.x, bug, review

#570 Fix member activities page on mobile
  app/assets/stylesheets/members/activities.css
  app/views/members/activities/partials/_view.html.haml
  app/views/members/activities/show.html.haml
Labels: 2.0.x, bug, review

#573 Always show committee labels
  app/assets/stylesheets/admin/activities.css
  app/views/admin/activities/index.html.haml
Labels: 2.0.x, bug, review

#398 Mailchimp synchronization
  .circleci/config.yml
  .rbenv-vars-sample
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/intro.css.scss
  app/controllers/admin/members_controller.rb
  app/controllers/api/webhook_controller.rb
  app/controllers/members/home_controller.rb
  app/controllers/public/home_controller.rb
  app/jobs/mailchimp_job.rb
  app/models/member.rb
  app/views/admin/members/edit.html.haml
  app/views/admin/members/new.html.haml
  app/views/admin/members/show.html.haml
  app/views/members/home/edit.html.haml
  app/views/public/home/index.html.haml
  config/app.yml
  config/application.rb
  config/environments/development.rb
  config/locales/en.yml
  config/locales/nl.yml
  config/routes.rb
Labels: feature, gdpr, review
